---
- name: Start Calibre Manager
  block:
    - name: Create Calibre Manager Directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - "{{ calibremanager_data_directory }}/data"

    - name: Calibre Docker Container
      docker_container:
        name: "{{ calibremanager_container_name }}"
        image: linuxserver/calibre
        pull: true
        volumes:
          - "{{ calibremanager_data_directory }}/data:/config:rw"
          - "{{ calibremanager_books_directory }}:/books:rw"
          - "{{ calibremanager_comics_directory }}:/comics:rw"
        env:
          TZ: "{{ ansible_nas_timezone }}"
          PUID: "{{ calibremanager_user_id }}"
          PGID: "{{ calibremanager_group_id }}"
          PASSWORD: "{{ calibremanager_password }}"
          CLI_ARGS: "{{ calibremanager_cli_args }}"
        ports:
          - "{{ calibremanager_port }}:8080"
          - "{{ calibremanager_webserver_port }}:8081"
        security_opts: "{{ calibremanager_security_opts }}"
        restart_policy: unless-stopped
        memory: "{{ calibremanager_memory }}"
        labels:
          traefik.enable: "{{ calibremanager_available_externally | string }}"
          traefik.http.routers.calibremanager.rule: "Host(`{{ calibremanager_hostname }}.{{ ansible_nas_domain }}`)"
          traefik.http.routers.calibremanager.tls.certresolver: "letsencrypt"
          traefik.http.routers.calibremanager.tls.domains[0].main: "{{ ansible_nas_domain }}"
          traefik.http.routers.calibremanager.tls.domains[0].sans: "*.{{ ansible_nas_domain }}"
          traefik.http.services.calibremanager.loadbalancer.server.port: "8080"
  when: calibremanager_enabled is true

- name: Stop Calibre Manager
  block:
    - name: Stop Calibre Manager
      docker_container:
        name: "{{ calibremanager_container_name }}"
        state: absent
  when: calibremanager_enabled is false
